ServerRoot "/etc/httpd"

#for http
#Listen 80

#for https
Listen 443

Include conf.modules.d/*.conf

IncludeOptional conf.d/*.conf

ErrorLog "logs/error_log"

<IfModule mime_module>
    TypesConfig /etc/mime.types
</IfModule>
