ServerRoot "/etc/httpd"

#for http
#Listen 80

#for https
Listen 443

Include conf.modules.d/*.conf

DocumentRoot "/var/www/html"

SSLEngine on
SSLCertificateFile /etc/letsencrypt/live/dhruvmishra.co.in/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/dhruvmishra.co.in/privkey.pem

ErrorDocument 404 /error_404.html
DirectoryIndex index.html

ErrorLog "logs/error_log"

<IfModule mime_module>
    TypesConfig /etc/mime.types
</IfModule>
