ServerRoot "/etc/httpd"

Listen 80

Include conf.modules.d/*.conf

DocumentRoot "/var/www/html"

DirectoryIndex index.html

ErrorLog "logs/error_log"

<IfModule mime_module>
    TypesConfig /etc/mime.types
</IfModule>
